# Generated by Django 5.1.3 on 2024-12-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
            ],
        ),
    ]
